
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
  - deployment: VMDeploy
    displayName: green
    pool:
      vmImage: 'Ubuntu-18.04'
    environment:
      name: anshitenv
      resourceType: VirtualMachine
      tags: green
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Downloading the source code from Azure blob storage container to the Azure VM..."